# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MicroDAQviewerUI.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1670, 1270)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.splitter_5 = QtWidgets.QSplitter(self.splitter_2)
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setObjectName("splitter_5")
        self.splitter_4 = QtWidgets.QSplitter(self.splitter_5)
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName("splitter_4")
        self.treeWidget = QtWidgets.QTreeWidget(self.splitter_4)
        self.treeWidget.setMinimumSize(QtCore.QSize(400, 0))
        self.treeWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.treeWidget.setDragEnabled(True)
        self.treeWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.treeWidget.setObjectName("treeWidget")
        self.tableWidget = QtWidgets.QTableWidget(self.splitter_4)
        self.tableWidget.setMinimumSize(QtCore.QSize(400, 0))
        self.tableWidget.setAcceptDrops(True)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setDragDropMode(QtWidgets.QAbstractItemView.DropOnly)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(200)
        self.gridLayoutWidget = QtWidgets.QWidget(self.splitter_5)
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.splitter_2)
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.triggerSource = QtWidgets.QLineEdit(self.horizontalLayoutWidget_4)
        self.triggerSource.setMaximumSize(QtCore.QSize(16777215, 30))
        self.triggerSource.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.triggerSource.setMouseTracking(False)
        self.triggerSource.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.triggerSource.setDragEnabled(False)
        self.triggerSource.setReadOnly(True)
        self.triggerSource.setObjectName("triggerSource")
        self.horizontalLayout_4.addWidget(self.triggerSource)
        self.simpleSearch = QtWidgets.QCheckBox(self.horizontalLayoutWidget_4)
        self.simpleSearch.setObjectName("simpleSearch")
        self.horizontalLayout_4.addWidget(self.simpleSearch)
        self.triggerOperator = QtWidgets.QComboBox(self.horizontalLayoutWidget_4)
        self.triggerOperator.setMaximumSize(QtCore.QSize(50, 16777215))
        self.triggerOperator.setBaseSize(QtCore.QSize(10, 0))
        self.triggerOperator.setObjectName("triggerOperator")
        self.triggerOperator.addItem("")
        self.triggerOperator.addItem("")
        self.triggerOperator.addItem("")
        self.horizontalLayout_4.addWidget(self.triggerOperator)
        self.triggerValue = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_4)
        self.triggerValue.setMaximumSize(QtCore.QSize(200, 16777215))
        self.triggerValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.triggerValue.setObjectName("triggerValue")
        self.horizontalLayout_4.addWidget(self.triggerValue)
        self.bPreviousTrigger = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.bPreviousTrigger.setMaximumSize(QtCore.QSize(200, 16777215))
        self.bPreviousTrigger.setObjectName("bPreviousTrigger")
        self.horizontalLayout_4.addWidget(self.bPreviousTrigger)
        self.bNextTrigger = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.bNextTrigger.setMaximumSize(QtCore.QSize(200, 16777215))
        self.bNextTrigger.setObjectName("bNextTrigger")
        self.horizontalLayout_4.addWidget(self.bNextTrigger)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_4.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.triggerArrayCombo = QtWidgets.QComboBox(self.horizontalLayoutWidget_4)
        self.triggerArrayCombo.setObjectName("triggerArrayCombo")
        self.triggerArrayCombo.addItem("")
        self.triggerArrayCombo.addItem("")
        self.triggerArrayCombo.addItem("")
        self.triggerArrayCombo.addItem("")
        self.triggerArrayCombo.addItem("")
        self.horizontalLayout_4.addWidget(self.triggerArrayCombo)
        self.label_11 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_4.addWidget(self.label_11)
        self.arrayPos = QtWidgets.QSpinBox(self.horizontalLayoutWidget_4)
        self.arrayPos.setEnabled(False)
        self.arrayPos.setMaximumSize(QtCore.QSize(200, 16777215))
        self.arrayPos.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.arrayPos.setMinimum(0)
        self.arrayPos.setMaximum(999999)
        self.arrayPos.setObjectName("arrayPos")
        self.horizontalLayout_4.addWidget(self.arrayPos)
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalSlider = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.horizontalSlider.setMaximumSize(QtCore.QSize(16777215, 30))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider.setTickInterval(1)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalLayout.addWidget(self.horizontalSlider)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setMaximumSize(QtCore.QSize(150, 30))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.spinEvent = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.spinEvent.setMaximumSize(QtCore.QSize(200, 30))
        self.spinEvent.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinEvent.setMaximum(999999999)
        self.spinEvent.setObjectName("spinEvent")
        self.horizontalLayout.addWidget(self.spinEvent)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.dateFirst = QtWidgets.QDateTimeEdit(self.verticalLayoutWidget)
        self.dateFirst.setReadOnly(False)
        self.dateFirst.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dateFirst.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(1752, 9, 14), QtCore.QTime(0, 0, 0)))
        self.dateFirst.setObjectName("dateFirst")
        self.horizontalLayout.addWidget(self.dateFirst)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.label_9)
        self.dateLast = QtWidgets.QDateTimeEdit(self.verticalLayoutWidget)
        self.dateLast.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dateLast.setObjectName("dateLast")
        self.horizontalLayout.addWidget(self.dateLast)
        self.bPlot = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.bPlot.setObjectName("bPlot")
        self.horizontalLayout.addWidget(self.bPlot)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_6.setMaximumSize(QtCore.QSize(500, 16777215))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.chainCombo = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.chainCombo.setMaximumSize(QtCore.QSize(200, 30))
        self.chainCombo.setObjectName("chainCombo")
        self.chainCombo.addItem("")
        self.chainCombo.addItem("")
        self.chainCombo.addItem("")
        self.chainCombo.addItem("")
        self.horizontalLayout_5.addWidget(self.chainCombo)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setMaximumSize(QtCore.QSize(250, 30))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.eventArrayCombo = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.eventArrayCombo.setEnabled(False)
        self.eventArrayCombo.setEditable(False)
        self.eventArrayCombo.setObjectName("eventArrayCombo")
        self.eventArrayCombo.addItem("")
        self.eventArrayCombo.addItem("")
        self.eventArrayCombo.addItem("")
        self.eventArrayCombo.addItem("")
        self.horizontalLayout_3.addWidget(self.eventArrayCombo)
        self.spinArrayPosition = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.spinArrayPosition.setEnabled(False)
        self.spinArrayPosition.setMaximumSize(QtCore.QSize(200, 30))
        self.spinArrayPosition.setMinimum(0)
        self.spinArrayPosition.setMaximum(999999999)
        self.spinArrayPosition.setProperty("value", 0)
        self.spinArrayPosition.setObjectName("spinArrayPosition")
        self.horizontalLayout_3.addWidget(self.spinArrayPosition)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_10.setMaximumSize(QtCore.QSize(250, 30))
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_7.addWidget(self.label_10)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.spinDecimation = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.spinDecimation.setEnabled(False)
        self.spinDecimation.setMaximumSize(QtCore.QSize(200, 30))
        self.spinDecimation.setMaximum(999999999)
        self.spinDecimation.setProperty("value", 1)
        self.spinDecimation.setObjectName("spinDecimation")
        self.horizontalLayout_7.addWidget(self.spinDecimation)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label.setMaximumSize(QtCore.QSize(200, 30))
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.spinChainEvents = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.spinChainEvents.setEnabled(False)
        self.spinChainEvents.setMaximumSize(QtCore.QSize(200, 30))
        self.spinChainEvents.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinChainEvents.setMaximum(999999999)
        self.spinChainEvents.setObjectName("spinChainEvents")
        self.horizontalLayout_2.addWidget(self.spinChainEvents)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_3.setMaximumSize(QtCore.QSize(10, 30))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.spinNEvents = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.spinNEvents.setMaximumSize(QtCore.QSize(200, 30))
        self.spinNEvents.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinNEvents.setReadOnly(True)
        self.spinNEvents.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spinNEvents.setMaximum(999999999)
        self.spinNEvents.setObjectName("spinNEvents")
        self.horizontalLayout_2.addWidget(self.spinNEvents)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addWidget(self.splitter_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setEnabled(False)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_6.addWidget(self.progressBar)
        self.bStop = QtWidgets.QPushButton(self.centralwidget)
        self.bStop.setEnabled(False)
        self.bStop.setObjectName("bStop")
        self.horizontalLayout_6.addWidget(self.bStop)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1670, 25))
        self.menuBar.setObjectName("menuBar")
        self.menuSettings = QtWidgets.QMenu(self.menuBar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menuBar)
        self.actionEnableDebugging = QtWidgets.QAction(MainWindow)
        self.actionEnableDebugging.setCheckable(True)
        self.actionEnableDebugging.setObjectName("actionEnableDebugging")
        self.menuSettings.addAction(self.actionEnableDebugging)
        self.menuBar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MicroDAQ Viewer"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "Item"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "parameter"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "value"))
        self.label_7.setText(_translate("MainWindow", "Trigger source:"))
        self.triggerSource.setToolTip(_translate("MainWindow", "<html><head/><body><p>Drag in variable from tree</p></body></html>"))
        self.simpleSearch.setToolTip(_translate("MainWindow", "<html><head/><body><p>If checked only the next event fullfilling the trigger criteria is searched. Else all events are investigated once. In consequence the next trigger search is faster in that case.</p></body></html>"))
        self.simpleSearch.setText(_translate("MainWindow", "SimpleSearch"))
        self.triggerOperator.setItemText(0, _translate("MainWindow", ">"))
        self.triggerOperator.setItemText(1, _translate("MainWindow", "<"))
        self.triggerOperator.setItemText(2, _translate("MainWindow", "="))
        self.bPreviousTrigger.setText(_translate("MainWindow", "Previous"))
        self.bNextTrigger.setText(_translate("MainWindow", "Next"))
        self.label_4.setText(_translate("MainWindow", "Array settings Index"))
        self.triggerArrayCombo.setItemText(0, _translate("MainWindow", "Mean"))
        self.triggerArrayCombo.setItemText(1, _translate("MainWindow", "Max"))
        self.triggerArrayCombo.setItemText(2, _translate("MainWindow", "Min"))
        self.triggerArrayCombo.setItemText(3, _translate("MainWindow", "Any element"))
        self.triggerArrayCombo.setItemText(4, _translate("MainWindow", "Position"))
        self.label_11.setText(_translate("MainWindow", "Index:"))
        self.arrayPos.setToolTip(_translate("MainWindow", "If set to -1 the whole array is tested."))
        self.label_5.setText(_translate("MainWindow", "Event/Event cluster:"))
        self.label_8.setText(_translate("MainWindow", "Selected Range:"))
        self.dateFirst.setDisplayFormat(_translate("MainWindow", "dd.MM.yy HH:mm:ss"))
        self.label_9.setText(_translate("MainWindow", "-"))
        self.dateLast.setDisplayFormat(_translate("MainWindow", "dd.MM.yy HH:mm:ss"))
        self.bPlot.setText(_translate("MainWindow", "Plot"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">Chain settings:</span></p></body></html>"))
        self.chainCombo.setItemText(0, _translate("MainWindow", "No chain"))
        self.chainCombo.setItemText(1, _translate("MainWindow", "Chain events"))
        self.chainCombo.setItemText(2, _translate("MainWindow", "Chain range"))
        self.chainCombo.setItemText(3, _translate("MainWindow", "Chain all"))
        self.label_2.setText(_translate("MainWindow", "Array position for chained Arrays"))
        self.eventArrayCombo.setItemText(0, _translate("MainWindow", "Mean"))
        self.eventArrayCombo.setItemText(1, _translate("MainWindow", "Max"))
        self.eventArrayCombo.setItemText(2, _translate("MainWindow", "Min"))
        self.eventArrayCombo.setItemText(3, _translate("MainWindow", "Position"))
        self.spinArrayPosition.setToolTip(_translate("MainWindow", "<html><head/><body><p>If index &lt; 0 the average is considered!</p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "Decimation"))
        self.label.setText(_translate("MainWindow", "Number of chained events"))
        self.label_3.setText(_translate("MainWindow", "/"))
        self.bStop.setText(_translate("MainWindow", "Stop"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.actionEnableDebugging.setText(_translate("MainWindow", "Enable debug messages"))

